name: Python tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  pybind:
    name: Test Python (${{ matrix.os }}, ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-11-arm]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
        exclude:
          - os: windows-11-arm
            python-version: "3.9"
          - os: windows-11-arm
            python-version: "3.10"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: msys2/setup-msys2@v2
      with:
        msystem: CLANGARM64
        update: true
        install: |
          mingw-w64-clang-aarch64-cmake
          mingw-w64-clang-aarch64-clang
          mingw-w64-clang-aarch64-flang
          mingw-w64-clang-aarch64-hdf5
          mingw-w64-clang-aarch64-ninja
          mingw-w64-clang-aarch64-netcdf
          mingw-w64-clang-aarch64-netcdf-fortran
          mingw-w64-clang-aarch64-openblas
          mingw-w64-clang-aarch64-pkgconf

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Add python build tools
      run: python -m pip install --upgrade wheel setuptools build scikit-build-core

    - name: Build wheel (Windows)  
      if: startsWith(matrix.os, 'windows')
      shell: msys2 {0}
      run: |
        cd pybind
        MSYS2_PYTHON=$(cygpath -u "$pythonLocation")
        "$MSYS2_PYTHON/python.exe" -m build --wheel --no-isolation --outdir wheelhouse

    - name: Repair wheel (Windows)
      if: startsWith(matrix.os, 'windows')
      shell: msys2 {0}
      run: |
        cd pybind
        for whl in wheelhouse/*.whl; do
          bash pybind/repair_wheel_windows.sh "$whl" wheelhouse
        done

    - name: Install wheel (Windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        cd pybind
        $whl = Get-ChildItem -Path "$(pwd)\wheelhouse\*.whl" | Select-Object -First 1
        pip install "$($whl.FullName)[test]"
    
